version: v0

runs:
  - name: Build Gommit
    tasks:
      - name: build
        runtime:
          type: pod
          arch: amd64
          containers:
            - image: golang:1.16-stretch
        steps:
          - clone:
          - restore_cache:
              keys:
                - pkg-cache-sum-{{ md5sum "go.sum" }}
              dest_dir: /go/pkg
          - restore_cache:
              keys:
                - build-cache-sum-{{ md5sum "go.sum" }}
              dest_dir: ~/.cache/go-build
          - run:
              name: build gommit
              command: make build 
          - save_cache:
              key: pkg-cache-sum-{{ md5sum "go.sum" }}
              contents:
                - source_dir: /go/pkg
          - save_cache:
              key: build-cache-sum-{{ md5sum "go.sum" }}
              contents:
                - source_dir: ~/.cache/go-build
